### ISSUE TITLE
REST API only available on localhost

### ISSUE THREAD

**Issue by pdurbin** [ProvTools/prov-cpl#5]
As a Dataverse developer, I want to run the prov-cpl REST service within Vagrant with the HTTP port exposed to my Mac ( https://github.com/IQSS/dataverse/issues/4364 ). Right now the service only runs on localhost (127.0.0.1) like this:

```
postgres@ubuntu-xenial:/prov-cpl/bindings/python/RestAPI$ python cpl-rest.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Can we have the REST service run on all IP addresses? A fix could be to change

`app.run()`

to

`app.run(host='0.0.0.0')`

in `bindings/python/RestAPI/cpl-rest.py` but I don't know if there's a better fix than that. I'm on 47a2ba4. Thanks.

**Comment by jacksonokuhn** [comment]
I can set it up to take -port -address args

**Comment by pdurbin** [comment]
@jacksonokuhn thanks for adding the `--host` arguments. As of this commit, I'm using it: https://github.com/IQSS/dataverse/commit/c43a40dad57cf5795f4bfeee602d7d2650e9b0ae
